server:
  port: 8089
  servlet:
    context-path: /shiro
    application-display-name: shiro

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  aop:
    auto: true
    proxy-target-class: true
    #------------------------------redis------------------------------
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#    shutdown-timeout: 100
#    jedis:
#      pool:
#        #连接池最大链接数
#        max-active: 8
#        #连接池最大阻塞时间（使用负值表示没有限制）默认为-1
#        max-wait: -1
#        #连接池中的最大空闲连接数
#        max-idle: 8
#        #连接池中的最小空闲连接数
#        min-idle: 0
#        #每ms运行一次空闲连接回收器（独立线程）
#        time-between-eviction-runs: 100000
#    timeout: 10000
#-----------------------------------------mybatis-plus-----------------------
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.babei.shiro.mapper
#------------------------------ 日志记录信息（服务器上记录日志文件） ------------------------------------------
logging:
  config: classpath:config/logback-spring.xml
  file:
    #    path: /usr/local/YMLog/wx
    path: c:/logtest/wx
#----------------------------- swagger应用 ----------------------------------
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  # 开启Swagger的Basic认证功能,默认是false   可以不开启
  basic:
    enable: true
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123
